# Alembic migration script template

"""Add SMS models and clustering

Revision ID: 732c617d2a29
Revises: 001
Create Date: 2026-05-27 01:58:34.870278

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '732c617d2a29'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    smsreportstatus = postgresql.ENUM('PENDING', 'CLUSTERED', 'VERIFIED', 'DISMISSED', name='smsreportstatus')
    smsreportstatus.create(op.get_bind(), checkfirst=True)
    
    incidentsource = postgresql.ENUM('WARDEN', 'PUBLIC_CLUSTER', 'SYSTEM', name='incidentsource')
    incidentsource.create(op.get_bind(), checkfirst=True)

    op.create_table('sms_reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('extracted_location', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CLUSTERED', 'VERIFIED', 'DISMISSED', name='smsreportstatus', create_type=False), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sms_reports_phone_number'), 'sms_reports', ['phone_number'], unique=False)
    op.create_index(op.f('ix_sms_reports_status'), 'sms_reports', ['status'], unique=False)
    op.create_index(op.f('ix_sms_reports_timestamp'), 'sms_reports', ['timestamp'], unique=False)
    op.create_table('trusted_wardens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('region', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trusted_wardens_phone_number'), 'trusted_wardens', ['phone_number'], unique=True)
    op.drop_constraint(op.f('admin_users_email_key'), 'admin_users', type_='unique')
    op.drop_constraint(op.f('admin_users_username_key'), 'admin_users', type_='unique')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=True)
    op.drop_index(op.f('idx_bot_messages_created_at'), table_name='bot_messages')
    op.drop_index(op.f('idx_bot_messages_platform'), table_name='bot_messages')
    op.drop_index(op.f('idx_bot_messages_platform_user_id'), table_name='bot_messages')
    op.add_column('incidents', sa.Column('source', sa.Enum('WARDEN', 'PUBLIC_CLUSTER', 'SYSTEM', name='incidentsource', create_type=False), nullable=True))
    op.drop_index(op.f('ix_incidents_location'), table_name='incidents', postgresql_using='gist')
    op.drop_index(op.f('ix_reports_location'), table_name='reports', postgresql_using='gist')
    op.drop_index(op.f('ix_users_location'), table_name='users', postgresql_using='gist')
    op.drop_constraint(op.f('users_phone_number_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_platform_id_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.drop_index(op.f('ix_users_platform_id'), table_name='users')
    op.create_index(op.f('ix_users_platform_id'), 'users', ['platform_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    smsreportstatus = postgresql.ENUM('PENDING', 'CLUSTERED', 'VERIFIED', 'DISMISSED', name='smsreportstatus')
    incidentsource = postgresql.ENUM('WARDEN', 'PUBLIC_CLUSTER', 'SYSTEM', name='incidentsource')
    
    op.drop_index(op.f('ix_users_platform_id'), table_name='users')
    op.create_index(op.f('ix_users_platform_id'), 'users', ['platform_id'], unique=False)
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=False)
    op.create_unique_constraint(op.f('users_platform_id_key'), 'users', ['platform_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_phone_number_key'), 'users', ['phone_number'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_users_location'), 'users', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_reports_location'), 'reports', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_incidents_location'), 'incidents', ['location'], unique=False, postgresql_using='gist')
    op.drop_column('incidents', 'source')
    op.create_index(op.f('idx_bot_messages_platform_user_id'), 'bot_messages', ['platform_user_id'], unique=False)
    op.create_index(op.f('idx_bot_messages_platform'), 'bot_messages', ['platform'], unique=False)
    op.create_index(op.f('idx_bot_messages_created_at'), 'bot_messages', ['created_at'], unique=False)
    op.drop_index(op.f('ix_admin_users_username'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_username'), 'admin_users', ['username'], unique=False)
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=False)
    op.create_unique_constraint(op.f('admin_users_username_key'), 'admin_users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('admin_users_email_key'), 'admin_users', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_trusted_wardens_phone_number'), table_name='trusted_wardens')
    op.drop_table('trusted_wardens')
    op.drop_index(op.f('ix_sms_reports_timestamp'), table_name='sms_reports')
    op.drop_index(op.f('ix_sms_reports_status'), table_name='sms_reports')
    op.drop_index(op.f('ix_sms_reports_phone_number'), table_name='sms_reports')
    op.drop_table('sms_reports')
    incidentsource.drop(op.get_bind(), checkfirst=True)
    smsreportstatus.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
